"""initial application schema

Revision ID: 1b13400551fd
Revises: 
Create Date: 2026-08-02 18:31:32.855151
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b13400551fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_table('cleanup_jobs',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('sandbox_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result_code', sa.String(length=200), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleanup_jobs_sandbox_id'), 'cleanup_jobs', ['sandbox_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('daily_quota_counters',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_microusd', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_daily_quota_user_day')
    )
    op.create_table('invites',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('invited_by', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by', sa.String(length=200), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.create_table('project_sources',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandboxes',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.Column('project_source_id', sa.String(length=200), nullable=True),
    sa.Column('template_id', sa.String(length=200), nullable=False),
    sa.Column('runtime_provider', sa.String(length=50), nullable=False),
    sa.Column('runtime_reference', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_source_id'], ['project_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandboxes_owner_status', 'sandboxes', ['owner_id', 'status'], unique=False)
    op.create_table('previews',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('sandbox_id', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('sandbox_id', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_sequence', sa.BigInteger(), nullable=False),
    sa.Column('compacted_summary_count', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_owner_status', 'sessions', ['owner_id', 'status'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('sandbox_id', sa.String(length=200), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('storage_reference', sa.String(length=1000), nullable=False),
    sa.Column('media_type', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_offsets',
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('stream_key', sa.String(length=500), nullable=False),
    sa.Column('last_sequence', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('stream_key')
    )
    op.create_table('turns',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('sandbox_id', sa.String(length=200), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('turn_id', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('sandbox_id', sa.String(length=200), nullable=True),
    sa.Column('turn_id', sa.String(length=200), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('estimated_cost_microusd', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_ledger')
    op.drop_table('approvals')
    op.drop_table('turns')
    op.drop_table('event_offsets')
    op.drop_table('artifacts')
    op.drop_index('ix_sessions_owner_status', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('previews')
    op.drop_index('ix_sandboxes_owner_status', table_name='sandboxes')
    op.drop_table('sandboxes')
    op.drop_table('project_sources')
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.drop_table('invites')
    op.drop_table('daily_quota_counters')
    op.drop_table('users')
    op.drop_index(op.f('ix_cleanup_jobs_sandbox_id'), table_name='cleanup_jobs')
    op.drop_table('cleanup_jobs')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
