import { mkdir, readFile, writeFile } from "node:fs/promises";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const root = fileURLToPath(new URL("..", import.meta.url));
const schemaPath = new URL("../backend/openapi.json", import.meta.url);
const outputRoot = new URL("../src/lib/api/generated/", import.meta.url);
const check = process.argv.includes("--check");

const header = `// Generated by scripts/generate_api_client.mjs. Do not edit by hand.

`;

const document = JSON.parse(await readFile(schemaPath, "utf8"));
const schema = header + astToString(await openapiTS(document));

const client = `${header}import { ApiClientError } from "../errors";
import type { components } from "./schema";

export type HealthResponse = components["schemas"]["HealthResponse"];
export type VersionResponse = components["schemas"]["VersionResponse"];
export type CapabilitiesResponse = components["schemas"]["CapabilitiesResponse"];
export type MeResponse = components["schemas"]["MeResponse"];
export type TemplatesResponse = components["schemas"]["TemplatesResponse"];
export type SandboxCreateRequest = components["schemas"]["SandboxCreateRequest"];
export type SandboxResponse = components["schemas"]["SandboxResponse"];
export type SandboxesResponse = components["schemas"]["SandboxesResponse"];
export type SessionCreateRequest = components["schemas"]["SessionCreateRequest"];
export type SessionResponse = components["schemas"]["SessionResponse"];
export type TurnCreateRequest = components["schemas"]["TurnCreateRequest"];
export type TurnResponse = components["schemas"]["TurnResponse"];
export type ApprovalResolutionRequest = components["schemas"]["ApprovalResolutionRequest"];
export type ApprovalResponse = components["schemas"]["ApprovalResponse"];
export type CancelResponse = components["schemas"]["CancelResponse"];
export type CompactionResponse = components["schemas"]["CompactionResponse"];
export type EventReplayResponse = components["schemas"]["EventReplayResponse"];
export type AgentEvent = components["schemas"]["AgentEventContract"];
export type FilesResponse = components["schemas"]["FilesResponse"];
export type FileContentResponse = components["schemas"]["FileContentResponse"];
export type ArtifactsResponse = components["schemas"]["ArtifactsResponse"];
export type ArtifactResponse = components["schemas"]["ArtifactResponse"];
export type SandboxDeleteResponse = components["schemas"]["SandboxDeleteResponse"];
export type RealtimeTicketRequest = components["schemas"]["RealtimeTicketRequest"];
export type RealtimeTicketResponse = components["schemas"]["RealtimeTicketResponse"];
export type AdminOverviewResponse = components["schemas"]["AdminOverviewResponse"];
export type ErrorEnvelope = components["schemas"]["ErrorEnvelope"];

export type ApiClientOptions = {
  baseUrl: string;
  getAccessToken?: () => Promise<string>;
  fetch?: typeof globalThis.fetch;
};

export class LunarForgeApiClient {
  private readonly baseUrl: string;
  private readonly getAccessToken?: () => Promise<string>;
  private readonly fetchImpl: typeof globalThis.fetch;

  constructor(options: ApiClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\\/$/, "");
    this.getAccessToken = options.getAccessToken;
    this.fetchImpl = options.fetch ?? globalThis.fetch.bind(globalThis);
  }

  private async request<T>(
    path: string,
    init: RequestInit = {},
    authenticated = false,
  ): Promise<T> {
    const headers = new Headers(init.headers);
    headers.set("Accept", "application/json");
    if (init.body) headers.set("Content-Type", "application/json");
    if (authenticated) {
      if (!this.getAccessToken) throw new Error("No access-token provider configured.");
      headers.set("Authorization", \`Bearer \${await this.getAccessToken()}\`);
    }
    const response = await this.fetchImpl(\`\${this.baseUrl}\${path}\`, {
      ...init,
      headers,
      cache: "no-store",
    });
    const body: unknown = await response.json();
    if (!response.ok) throw new ApiClientError(response.status, body as ErrorEnvelope);
    return body as T;
  }

  health = () => this.request<HealthResponse>("/api/v1/health");
  version = () => this.request<VersionResponse>("/api/v1/version");
  capabilities = () => this.request<CapabilitiesResponse>("/api/v1/capabilities");
  templates = () => this.request<TemplatesResponse>("/api/v1/templates");
  me = () => this.request<MeResponse>("/api/v1/me", {}, true);
  listSandboxes = () => this.request<SandboxesResponse>("/api/v1/sandboxes", {}, true);
  getSandbox = (sandboxId: string) =>
    this.request<SandboxResponse>(\`/api/v1/sandboxes/\${encodeURIComponent(sandboxId)}\`, {}, true);
  createSandbox = (body: SandboxCreateRequest) =>
    this.request<SandboxResponse>("/api/v1/sandboxes", {
      method: "POST",
      body: JSON.stringify(body),
    }, true);
  resetSandbox = (sandboxId: string) =>
    this.request<SandboxResponse>(
      \`/api/v1/sandboxes/\${encodeURIComponent(sandboxId)}/reset\`,
      { method: "POST" },
      true,
    );
  deleteSandbox = (sandboxId: string) =>
    this.request<SandboxDeleteResponse>(
      \`/api/v1/sandboxes/\${encodeURIComponent(sandboxId)}\`,
      { method: "DELETE" },
      true,
    );
  listFiles = (sandboxId: string) =>
    this.request<FilesResponse>(
      \`/api/v1/sandboxes/\${encodeURIComponent(sandboxId)}/files\`,
      {},
      true,
    );
  getFile = (sandboxId: string, path: string) =>
    this.request<FileContentResponse>(
      \`/api/v1/sandboxes/\${encodeURIComponent(sandboxId)}/file?path=\${encodeURIComponent(path)}\`,
      {},
      true,
    );
  getSession = (sessionId: string) =>
    this.request<SessionResponse>(\`/api/v1/sessions/\${encodeURIComponent(sessionId)}\`, {}, true);
  createSession = (sandboxId: string, body: SessionCreateRequest = {}) =>
    this.request<SessionResponse>(
      \`/api/v1/sandboxes/\${encodeURIComponent(sandboxId)}/sessions\`,
      { method: "POST", body: JSON.stringify(body) },
      true,
    );
  createTurn = (sessionId: string, body: TurnCreateRequest) =>
    this.request<TurnResponse>(
      \`/api/v1/sessions/\${encodeURIComponent(sessionId)}/turns\`,
      { method: "POST", body: JSON.stringify(body) },
      true,
    );
  resolveApproval = (
    sessionId: string,
    approvalId: string,
    body: ApprovalResolutionRequest,
  ) =>
    this.request<ApprovalResponse>(
      \`/api/v1/sessions/\${encodeURIComponent(sessionId)}/approvals/\${encodeURIComponent(approvalId)}\`,
      { method: "POST", body: JSON.stringify(body) },
      true,
    );
  cancelTurn = (sessionId: string) =>
    this.request<CancelResponse>(
      \`/api/v1/sessions/\${encodeURIComponent(sessionId)}/cancel\`,
      { method: "POST" },
      true,
    );
  compactSession = (sessionId: string) =>
    this.request<CompactionResponse>(
      \`/api/v1/sessions/\${encodeURIComponent(sessionId)}/compact\`,
      { method: "POST" },
      true,
    );
  replayEvents = (sessionId: string, afterSequence = 0) =>
    this.request<EventReplayResponse>(
      \`/api/v1/sessions/\${encodeURIComponent(sessionId)}/events?after_sequence=\${afterSequence}\`,
      {},
      true,
    );
  listArtifacts = (sessionId: string) =>
    this.request<ArtifactsResponse>(
      \`/api/v1/sessions/\${encodeURIComponent(sessionId)}/artifacts\`,
      {},
      true,
    );
  createRealtimeTicket = (body: RealtimeTicketRequest) =>
    this.request<RealtimeTicketResponse>("/api/v1/realtime/tickets", {
      method: "POST",
      body: JSON.stringify(body),
    }, true);
  adminOverview = () =>
    this.request<AdminOverviewResponse>("/api/v1/admin/overview", {}, true);
}
`;

const index = `${header}export * from "./client";
export type { components, operations, paths } from "./schema";
`;

const outputs = new Map([
  [new URL("schema.ts", outputRoot), schema],
  [new URL("client.ts", outputRoot), client],
  [new URL("index.ts", outputRoot), index],
]);

if (!check) await mkdir(outputRoot, { recursive: true });

let stale = false;
for (const [url, content] of outputs) {
  if (check) {
    let existing = "";
    try {
      existing = await readFile(url, "utf8");
    } catch {
      // A missing output is stale.
    }
    if (existing !== content) {
      stale = true;
      process.stderr.write(`Generated API client is stale: ${fileURLToPath(url)}\n`);
    }
  } else {
    await writeFile(url, content, "utf8");
    process.stdout.write(`Wrote ${relative(root, fileURLToPath(url))}\n`);
  }
}

if (stale) process.exitCode = 1;
