"""Create a bounded, reviewable fingerprint of approved LunarForge core sources."""

from __future__ import annotations

import ast
import hashlib
import os
from pathlib import Path
import re
import subprocess
import sys
import tomllib
from datetime import date


CORE_PATH_ENV = "LUNAR_FORGE_CORE_PATH"
OUTPUT_PATH = Path("content/docs/_generated/core-source-snapshot.md")
MAX_FILE_BYTES = 750_000
MAX_TOTAL_BYTES = 4_000_000
ALLOWED_SOURCES = (
    "README.md",
    "docs/website-copy.md",
    "pyproject.toml",
    "lunar_forge/__init__.py",
    "lunar_forge/public_api.py",
    "lunar_forge/events.py",
    "lunar_forge/approvals.py",
    "lunar_forge/config.py",
    "lunar_forge/mcp/config.py",
    "lunar_forge/plugins/loader.py",
    "tests/test_public_api.py",
    "tests/test_events.py",
    "tests/test_approvals.py",
    "tests/test_config.py",
    "tests/test_mcp_config.py",
)
GENERATED_START = "<!-- GENERATED:START -->"
GENERATED_END = "<!-- GENERATED:END -->"
HUMAN_START = "<!-- HUMAN:START -->"
HUMAN_END = "<!-- HUMAN:END -->"


def resolve_allowed_source(core_root: Path, relative_path: str) -> Path:
    """Resolve one allowlisted path without following it outside the core root."""

    normalized = relative_path.replace("\\", "/")
    parts = Path(normalized).parts
    if any(part.casefold() == ".agent" for part in parts):
        raise ValueError("The core .agent runtime directory is never readable.")
    if normalized not in ALLOWED_SOURCES:
        raise ValueError(f"Core source is not allowlisted: {relative_path}")

    root = core_root.expanduser().resolve()
    candidate = (root / normalized).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"Core source escaped its root: {relative_path}") from exc
    if not candidate.is_file():
        raise FileNotFoundError(f"Allowlisted core source is missing: {normalized}")
    if candidate.stat().st_size > MAX_FILE_BYTES:
        raise ValueError(f"Allowlisted core source is too large: {normalized}")
    return candidate


def read_allowlist(core_root: Path) -> dict[str, bytes]:
    """Read exactly the declared sources and enforce a total byte bound."""

    sources: dict[str, bytes] = {}
    total = 0
    for relative_path in ALLOWED_SOURCES:
        content = resolve_allowed_source(core_root, relative_path).read_bytes()
        total += len(content)
        if total > MAX_TOTAL_BYTES:
            raise ValueError("Allowlisted core sources exceed the total byte limit.")
        sources[relative_path] = content
    return sources


def python_all(source: bytes, filename: str) -> tuple[str, ...]:
    """Read a literal module __all__ without importing core code."""

    tree = ast.parse(source.decode("utf-8"), filename=filename)
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "__all__"
            for target in node.targets
        ):
            value = ast.literal_eval(node.value)
            if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
                raise ValueError(f"{filename}: __all__ must be a literal string list")
            return tuple(value)
    raise ValueError(f"{filename}: no literal __all__ found")


def git_metadata(core_root: Path) -> tuple[str, str]:
    """Read the core commit and exact tag without changing repository config."""

    safe = f"safe.directory={core_root.resolve().as_posix()}"

    def run(*arguments: str) -> str:
        result = subprocess.run(
            ["git", "-c", safe, "-C", str(core_root), *arguments],
            check=True,
            capture_output=True,
            text=True,
            timeout=10,
        )
        return result.stdout.strip()

    commit = run("rev-parse", "HEAD")
    try:
        tag = run("describe", "--tags", "--exact-match", "HEAD")
    except subprocess.CalledProcessError:
        tag = "none"
    return commit, tag


def render_snapshot(
    sources: dict[str, bytes],
    *,
    commit: str,
    tag: str,
    sync_date: str,
) -> str:
    """Render metadata and exports only; source bodies are never copied."""

    root_exports = python_all(sources["lunar_forge/__init__.py"], "lunar_forge/__init__.py")
    module_exports = python_all(
        sources["lunar_forge/public_api.py"],
        "lunar_forge/public_api.py",
    )
    package = tomllib.loads(sources["pyproject.toml"].decode("utf-8"))["project"]
    lines = [
        "# LunarForge core source snapshot",
        "",
        GENERATED_START,
        "",
        "This section is generated by `scripts/sync_core_docs.py`. It records bounded",
        "metadata for review; it does not copy the core manuals or source bodies.",
        "",
        f"- Source commit: `{commit}`",
        f"- Exact source tag: `{tag}`",
        f"- Sync date: `{sync_date}`",
        f"- Distribution: `{package['name']}`",
        f"- Version: `{package['version']}`",
        f"- Requires Python: `{package['requires-python']}`",
        "",
        "## Allowlisted source fingerprints",
        "",
        "| Path | Bytes | SHA-256 |",
        "| --- | ---: | --- |",
    ]
    for relative_path, content in sources.items():
        digest = hashlib.sha256(content).hexdigest()
        lines.append(f"| `{relative_path}` | {len(content)} | `{digest}` |")
    lines.extend(
        [
            "",
            "## Public exports observed",
            "",
            "Root `lunar_forge` exports: " + ", ".join(f"`{name}`" for name in root_exports) + ".",
            "",
            "`lunar_forge.public_api` exports: "
            + ", ".join(f"`{name}`" for name in module_exports)
            + ".",
            "",
            GENERATED_END,
            "",
            "## Human review notes",
            "",
            HUMAN_START,
            "",
            "Add reviewed interpretation here. This block is preserved across syncs.",
            "",
            HUMAN_END,
            "",
        ]
    )
    return "\n".join(lines)


def preserve_human_notes(existing: str, generated: str) -> str:
    """Carry the explicitly marked human block into a newly rendered snapshot."""

    pattern = re.compile(
        rf"{re.escape(HUMAN_START)}(?P<body>[\s\S]*?){re.escape(HUMAN_END)}"
    )
    current = pattern.search(existing)
    replacement = pattern.search(generated)
    if current is None or replacement is None:
        return generated
    return generated[: replacement.start("body")] + current.group("body") + generated[replacement.end("body") :]


def main() -> int:
    configured = os.environ.get(CORE_PATH_ENV)
    if not configured:
        print(f"{CORE_PATH_ENV} must point to the LunarForge core repository.", file=sys.stderr)
        return 2
    core_root = Path(configured).expanduser().resolve()
    if not core_root.is_dir():
        print(f"Core repository is unavailable: {core_root}", file=sys.stderr)
        return 2

    sources = read_allowlist(core_root)
    commit, tag = git_metadata(core_root)
    output = Path.cwd() / OUTPUT_PATH
    existing = output.read_text(encoding="utf-8") if output.exists() else ""
    check = "--check" in sys.argv
    match = re.search(r"- Sync date: `([^`]+)`", existing) if check else None
    selected_date = match.group(1) if match else date.today().isoformat()
    rendered = render_snapshot(
        sources,
        commit=commit,
        tag=tag,
        sync_date=selected_date,
    )
    rendered = preserve_human_notes(existing, rendered)

    if check:
        if existing != rendered:
            print("Core source snapshot is stale. Run npm run docs:sync.", file=sys.stderr)
            return 1
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_PATH} from {len(ALLOWED_SOURCES)} allowlisted sources.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
