"""Shared transport and owner-funded policy limits.

These values deliberately mirror ``AGENTS.md``.  They are constants rather
than deployment knobs so a production environment cannot silently weaken the
portfolio deployment's funding or lifetime policy.
"""

MAX_PROMPT_CHARACTERS = 50_000
MAX_EVENT_PAYLOAD_CHARACTERS = 100_000
MAX_FILE_RESPONSE_CHARACTERS = 1_000_000
MAX_REPLAY_EVENTS = 2_000
MAX_EVENT_STREAM_ITEMS = 2_000
MAX_CONTROL_STREAM_ITEMS = 200
MAX_CONTROL_PAYLOAD_CHARACTERS = 20_000
MAX_AUDIT_DETAIL_CHARACTERS = 20_000

OWNER_FUNDED_PROVIDER = "openai"
OWNER_FUNDED_MAX_REASONING_EFFORT = "high"
OWNER_FUNDED_TURNS_PER_USER_PER_DAY = 20
OWNER_FUNDED_ACTIVE_SANDBOXES_PER_USER = 1
OWNER_FUNDED_TURN_TIMEOUT_SECONDS = 15 * 60
OWNER_FUNDED_USER_DAILY_COST_MICROUSD = 3_000_000
OWNER_FUNDED_GLOBAL_DAILY_COST_MICROUSD = 10_000_000

SANDBOX_INACTIVITY_TTL_SECONDS = 30 * 60
MAX_RUNTIME_COMMAND_CHARACTERS = 20_000
MAX_RUNTIME_COMMAND_OUTPUT_CHARACTERS = 100_000
MAX_RUNTIME_FILE_ENTRIES = 10_000
MAX_RUNTIME_ARCHIVE_BYTES = 10_485_760
MAX_RUNTIME_ARTIFACT_BYTES = 10_485_760
MAX_PUBLIC_GIT_URL_CHARACTERS = 2_048
MAX_PUBLIC_GIT_CLONE_SECONDS = 120
MAX_PUBLIC_GIT_CLONE_BYTES = 250_000_000
RETAINED_METADATA_DAYS = 30

WEBSOCKET_TICKET_MAX_CHARACTERS = 512
PREVIEW_TICKET_MAX_CHARACTERS = 512
